### ISSUE TITLE
myeclipse报错。

### ISSUE THREAD

**Issue by liuzhenyilzhy** [qiuqiu3/pptv#3]
错误: 找不到或无法加载主类 org.mockito.asm.util.ASMifierClassVisitor
原因: java.lang.ClassNotFoundException: org.mockito.asm.util.ASMifierClassVisitor
楼主您好！运行报错。
完全菜鸟，不知哪里不对。
![QQ截图20190317171016](https://user-images.githubusercontent.com/31317115/54488391-39b9e580-48dc-11e9-89ee-e399947ed343.png)
![QQ截图20190317170926](https://user-images.githubusercontent.com/31317115/54488392-3aeb1280-48dc-11e9-9966-d9f7ccb513b9.png)
我是如上两图导入项目的。
![QQ截图20190317173625](https://user-images.githubusercontent.com/31317115/54488395-3d4d6c80-48dc-11e9-87f7-2455e4e04987.png)
然后在左侧栏，选中163那一项，右键，run as   java application。
然后就提示错误。
问题出在哪儿？我该怎么办？
或者也可以邮箱联系我，18553366227@163.com。
谢谢您的解答！

**Comment by qiuqiu3** [comment]
兄弟你好你的版本好新啊，我用的是jdk1.7开发环境，myeclipse是2015，新版的myeclipse没条件测试，你的报错好像是和汇编有关系的，而且我并没有引用这方面的库。我的建议是找个myeclipse 2015测试环境，并且maven在3.0以上，运行成功后你可以把mvn项目转成eclipse项目，这样可以把项目（包含jar包）复现到新环境中。

**Comment by liuzhenyilzhy** [comment]
感谢大佬回复！我完全菜鸟，完全不懂编程。大佬的回复，我也是似懂非懂，试试再看。谢谢！我先试试。

**Comment by liuzhenyilzhy** [comment]
大神，您好！
还是要请教一下，
我继续试了一下，还是用的上次的myeclipse，版本是2018.8。jdk按照百度的方法安装的jdk1.7，maven也是按照百度的方法安装的3.6.0。如图，maven应该是装好了。
![捕获5](https://user-images.githubusercontent.com/31317115/54861342-84b37d00-4d62-11e9-98fa-795ac3ef9ccd.PNG)
现在是这样，
载入项目文件夹后，报错如下图，
![捕获4](https://user-images.githubusercontent.com/31317115/54861371-e8d64100-4d62-11e9-9af5-a13067d249e7.PNG)
其中四项警告，的第四项，build path。。。等等等，我已经通过上面说的安装jdk1.7后稀里糊涂的解决了。
前三项警告，百度了一下，说是把pom.xml里的version 2.9.2删掉即可，我试过，确实没有警告了。
但我考虑可能是spring boot版本的问题，也从github下载了最新版的spring boot，但是百度了一下，还是没弄明白怎么安装使用，使我新下载的spring boot能够被代码所使用，怎么让我新下载的spring boot与代码之间产生联系，代码可以调用。有些名词，什么搭建，配置，安装，部署，我也搞不明白什么意思。
这都不管，就是怎么能让新的spring boot起作用。
然后，错误共有8项，现在因为spring boot的问题没有解决，我也不知道是不是与spring boot有关。解决了spring boot，是不是这8项错误就得到解决了。
再接下来，
从左侧的项目浏览器，右键点击163，
右键run as java app后，如下图，
![捕获](https://user-images.githubusercontent.com/31317115/54861504-c5ac9100-4d64-11e9-9133-5b29780725aa.PNG)
选type？这个选哪个？
上次的问题可能就是因为我选了那个ASM出了问题，这一步应该怎么做？我选了pptvprocessor，还是选那个app-com.pptv.test?
然后如下图，
![捕获2](https://user-images.githubusercontent.com/31317115/54861531-7581fe80-4d65-11e9-85b5-16e8aab9fa8d.PNG)
我猜这个是那8项错误的一个提示，
点proceed，然后，
![捕获3](https://user-images.githubusercontent.com/31317115/54861550-aeba6e80-4d65-11e9-9a75-197e176341c6.PNG)
有五条警告。
谢谢！

**Comment by liuzhenyilzhy** [comment]
稀里糊涂一通搞之后，警告和错误都解决了。
现在就是run as java app那里了。
选哪个？
第一种情况，选择APP-com.pptv.test如下图，
![QQ截图20190323210126](https://user-images.githubusercontent.com/31317115/54866491-4c865b80-4daf-11e9-94ae-52b413e90ab6.png)
![QQ截图20190323210238](https://user-images.githubusercontent.com/31317115/54866492-514b0f80-4daf-11e9-89fa-a981b77018e6.png)
全文如下：
21:01:35.805 [main] DEBUG org.springframework.boot.devtools.settings.DevToolsSettings - Included patterns for restart : []
21:01:35.807 [main] DEBUG org.springframework.boot.devtools.settings.DevToolsSettings - Excluded patterns for restart : [/spring-boot-starter/target/classes/, /spring-boot-autoconfigure/target/classes/, /spring-boot-starter-[\w-]+/, /spring-boot/target/classes/, /spring-boot-actuator/target/classes/, /spring-boot-devtools/target/classes/]
21:01:35.808 [main] DEBUG org.springframework.boot.devtools.restart.ChangeableUrls - Matching URLs for reloading : [file:/H:/pptv%20parser/pptv-master/target/classes/]
qiuqiu
2019-03-23 21:01:36.064  INFO 21692 --- [  restartedMain] com.pptv.test.App                        : Starting App on DESKTOP-H6TQQS7 with PID 21692 (started by liu in H:\pptv parser\pptv-master)
2019-03-23 21:01:36.066  INFO 21692 --- [  restartedMain] com.pptv.test.App                        : No active profile set, falling back to default profiles: default
2019-03-23 21:01:36.112  INFO 21692 --- [  restartedMain] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@7669929e: startup date [Sat Mar 23 21:01:36 CST 2019]; root of context hierarchy
2019-03-23 21:01:36.797  INFO 21692 --- [  restartedMain] com.pptv.test.config.RedisConfig         : redis info：127.0.0.1:6379
2019-03-23 21:01:36.986  INFO 21692 --- [  restartedMain] o.s.b.d.a.OptionalLiveReloadServer       : LiveReload server is running on port 35729
2019-03-23 21:01:37.014  INFO 21692 --- [  restartedMain] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
2019-03-23 21:01:37.172  INFO 21692 --- [  restartedMain] us.codecraft.webmagic.Spider             : Spider v.pptv.com started!
2019-03-23 21:01:37.515  INFO 21692 --- [pool-1-thread-1] u.c.w.downloader.HttpClientDownloader    : downloading page success http://v.pptv.com/show/qk3vbLiahSojradE.html
2019-03-23 21:01:37.736 ERROR 21692 --- [pool-1-thread-1] us.codecraft.webmagic.Spider             : process request Request{url='http://v.pptv.com/show/qk3vbLiahSojradE.html', method='null', extras=null, priority=0, headers={}, cookies={}} error

java.lang.NumberFormatException: For input string: "2317896993"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[na:1.7.0_80]
	at java.lang.Integer.parseInt(Integer.java:495) ~[na:1.7.0_80]
	at java.lang.Integer.valueOf(Integer.java:582) ~[na:1.7.0_80]
	at com.pptv.test.utils.PPTVUtil.parseXml(PPTVUtil.java:73) ~[classes/:na]
	at com.pptv.test.utils.PPTVUtil.getVideo(PPTVUtil.java:30) ~[classes/:na]
	at com.pptv.test.service.PPTVProcessor.process(PPTVProcessor.java:33) ~[classes/:na]
	at us.codecraft.webmagic.Spider.onDownloadSuccess(Spider.java:414) ~[webmagic-core-0.7.3.jar:na]
	at us.codecraft.webmagic.Spider.processRequest(Spider.java:406) ~[webmagic-core-0.7.3.jar:na]
	at us.codecraft.webmagic.Spider.access$000(Spider.java:61) ~[webmagic-core-0.7.3.jar:na]
	at us.codecraft.webmagic.Spider$1.run(Spider.java:320) ~[webmagic-core-0.7.3.jar:na]
	at us.codecraft.webmagic.thread.CountableThreadPool$1.run(CountableThreadPool.java:74) [webmagic-core-0.7.3.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_80]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_80]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_80]

2019-03-23 21:01:37.736  INFO 21692 --- [  restartedMain] us.codecraft.webmagic.Spider             : Spider v.pptv.com closed! 1 pages downloaded.
2019-03-23 21:01:37.738  INFO 21692 --- [  restartedMain] com.pptv.test.App                        : Started App in 1.913 seconds (JVM running for 2.249)
2019-03-23 21:01:37.740  INFO 21692 --- [      Thread-10] s.c.a.AnnotationConfigApplicationContext : Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@7669929e: startup date [Sat Mar 23 21:01:36 CST 2019]; root of context hierarchy
2019-03-23 21:01:37.742  INFO 21692 --- [      Thread-10] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans on shutdown
第二种情况，选PPTVProcessor-com.pptv.test.service如下图，
![QQ截图20190323210916](https://user-images.githubusercontent.com/31317115/54866534-f960d880-4daf-11e9-9746-ab966544379a.png)
第二种情况没发现什么异常。
第一种情况，一上来，三个debug不知道有没有影响，
然后有个：
2019-03-23 21:01:37.736 ERROR 21692 --- [pool-1-thread-1] us.codecraft.webmagic.Spider             : process request Request{url='http://v.pptv.com/show/qk3vbLiahSojradE.html', method='null', extras=null, priority=0, headers={}, cookies={}} error
是不是出问题了？接下来我该做什么？
谢谢！

**Comment by qiuqiu3** [comment]
兄弟啊你真执着，你现在已经成功运行了啊，恭喜你又进步了，java.lang.NumberFormatException报错指的是超出int的范围，按道理不应该有这么大的数字，另外运行项目直接右键项目->run as->Java Application就行。谢谢你！剩下一些warning不用管能运行就OK了

**Comment by liuzhenyilzhy** [comment]
哈哈，谢谢大神！看个球不容易，还能学技术。
进一步运行，现在发现三个问题，
第一个问题：
如下两个链接，
是同一场亚冠比赛，
一集锦：
http://sports.pptv.com/sportslive?sectionid=153180&matchid=259898
分享地址：
http://v.pptv.com/show/J4KoJ4ic1ZaM7jPddzQ.html
二全场：
http://sports.pptv.com/vod/29844388/8102470?from=pptv
分享地址：
http://v.pptv.com/show/pAUlogpw4B7IeibBGtg.html
运行app如下，
集锦
![QQ截图20190325090346](https://user-images.githubusercontent.com/31317115/54890509-a2a8eb00-4ee4-11e9-8c02-db139cf4c42a.png)
全场
![QQ截图20190325091610](https://user-images.githubusercontent.com/31317115/54890566-ef8cc180-4ee4-11e9-808e-c3381758fce8.png)
集锦得到了结果，而全场还是卡在java.lang.NumberFormatException报错得不到结果。
第二个问题，
两者运行pptvprocessor，仍然得到的是原来英超精华的结果，什么问题？还有别的地方需要更改视频地址？
![QQ截图20190325091821](https://user-images.githubusercontent.com/31317115/54890830-11d30f00-4ee6-11e9-8a9e-b344f8819bb2.png)
![QQ截图20190325091048](https://user-images.githubusercontent.com/31317115/54890833-17c8f000-4ee6-11e9-9393-0c787d1101ba.png)
第三个问题，
集锦得到结果后，console内的内容，ctrl+a全选，复制粘贴，得不到全部的文字信息，
只能得到如下部分：
2019-03-25 08:59:13.033  INFO 8688 --- [  restartedMain] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
2019-03-25 08:59:13.201  INFO 8688 --- [  restartedMain] us.codecraft.webmagic.Spider             : Spider v.pptv.com started!
2019-03-25 08:59:13.513  INFO 8688 --- [pool-1-thread-1] u.c.w.downloader.HttpClientDownloader    : downloading page success http://v.pptv.com/show/J4KoJ4ic1ZaM7jPddzQ.html
标题:亚冠-佩莱梅开二度 鲁能2-2鹿岛两连平
缩略图: http://v.img.pplive.cn/cs128x72/85/b3/85b37b9680b0cb6b12b3e29347a75f0a/1552383643259.jpg

[标清-11.0MB]
http://140.207.204.56/0/47921c30c45373750c21feb046c45729.mp4?fpp.ver=1.3.0.24&key=df6f4fb95bd2e66c027d73122055ed37
只能得到以上部分，
卡在了
&k=313bdfab93a6c5f1cf3ef4894e977adb-841d-1545114345%26bppcataid%3D38&type=web.fpp前面的那个空格，
再试一试每一行单独复制，都是这样，复制不全，都在&k=这个地方前面有一个空格卡住了，
不知道哪里问题。
![QQ截图20190325094922](https://user-images.githubusercontent.com/31317115/54890950-9c1b7300-4ee6-11e9-9010-0d6396e26386.png)
以上三个问题，谢谢大佬！
